---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: test
  labels:
    app: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: cnt
          image: terezabisharyan/simple-nodejs:${GITHUB_SHA::7}
          ports:
            - containerPort: 3000
