---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia
  namespace: test
  labels:
    app: kubia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
        - name: kubia-cnt
          image: terezabisharyan/simple-nodejs:523cfee
          ports:
            - containerPort: 80
